config/routes.rb
Rails.application.routes.draw do

# Serve websocket cable requests in-process
 mount ActionCable.server => '/cable'

 # root 'pages#home'
 root 'pages#home'

resources :posts
resources :locations
resources :messages, only:[:create]
resources :sessions, only:[:new, :destroy, :create]

resources :users do
  resources :chats, only: [:index, :show, :create]
end


  get '/signup', to: 'users#new'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'





end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :posts, dependent: :destroy
  belongs_to :location, optional: true
  has_one_attached :avatar

  # Chat Related
   has_many :messages
   has_many :subscriptions
   has_many :chats, through: :subscriptions

  validates :first_name, :last_name, presence: true
  validates :username, presence: true, uniqueness: true, :uniqueness => { :case_sensitive => false }
  validates :email, presence: true, uniqueness: true, :uniqueness => { :case_sensitive => false }
  validates :password, confirmation: true, length: { minimum: 6 }, allow_nil: true
  validates :purchased, default: false

# Chat Related
  def existing_chats_users
    existing_chat_users = []
    self.chats.each do |chat|
    existing_chat_users.concat(chat.subscriptions.where.not(user_id: self.id).map {|subscription| subscription.user})
    end
    existing_chat_users.uniq
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :verify_authenticity_token

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.valid?
      @user.save
      flash[:notice] = "User created!"
      log_in @user
      flash[:success] = "Welcome"
      redirect_to @user
    else
      flash[:notice] = "#{@user.errors.messages}"
      render 'new'
    end
  end


  def show
    @user = User.find_by(id: params[:id])
    if session[:user_id] == @user.id
  else
    redirect_to current_user
    end
  end

  def index
      @user = User.all
      if current_user == nil
    else
      redirect_to root_path
    end
  end

  def edit
    @user = User.find_by(id: params[:id])
    if current_user.id != @user.id
      redirect_to root_path
    end
  end

  def update
    @user = User.find_by(id: params[:id])
    if @user.update(user_params)
      flash[:notice] = "User updated"
       redirect_to @user
    else
      puts "#{@user.errors.messages}"
      render 'new'
    end
  end

  def destroy
    @user = User.find_by(id: params[:id])
    @user.destroy
    session[:user_id] = nil
    redirect_to login_path
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :username, :password, :password_confirmation, :location_string, :purchased, :avatar)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/destroy.js.erb
$('.delete').bind('ajax:sucess', function() {
    $(this).closest('tr').fadeOut()
});

app/views/users/edit.html.erb
<div class="container mx-auto container-margin">
  <h1 class="font-weight-normal text-center mb-3">Edit</h1>
  <div class="row">
    <div class="col-md-12 form-signin ">
      <%= form_for(@user) do |u| %>
        <div class="form-signin"><%= u.text_field :first_name, placeholder: "First Name", class: "form-control"%></div>
        <div class="form-signin"><%= u.text_field :last_name, placeholder: "Last Name", class: "form-control" %></div>
        <div class="form-signin"><%= u.text_field :username, placeholder: "Username", class: "form-control" %></div>
        <div class="form-signin"><%= u.email_field :email, placeholder: "Email", class: "form-control" %></div>
        <div class="form-signin"><%= u.password_field :password, placeholder: "Password", class: "form-control" %></div>
        <div class="form-signin"><%= u.password_field :password_confirmation, placeholder: "Password Confirmation", class: "form-control" %></div>
        <div class="form-signin"><%= u.file_field :avatar, class: "form-control" %></div>
        <div class="form-signin"><%= u.text_field :location_string, class: "form-control" %></div>
        <div class="form-signin"> <%= u.submit class: "btn btn-lg btn-primary btn-block special-btn-color" %></div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<h2>All Users</h2>

 <% @user.each do |u| %>
  <label>First Name:</label><br>
  <%= u.first_name %><br>

  <label>Last Name:</label><br>
  <%= u.last_name %><br>

  <label>Email:</label><br>
  <%= u.email %>

  <br>
  <br>

   <% end %>

app/views/users/new.html.erb
<div class="container mx-auto container-margin">
    <div class="row">
      <div class="col-md-12 form-signin">
        <h1 class="font-weight-normal text-center mb-3">Sign up!</h1>
        <%= form_for(@user) do |u| %>
        
          <div class="form-signin"><%= u.text_field :first_name, placeholder: "First Name", class: "form-control"%></div>
          <div class="form-signin"><%= u.text_field :last_name, placeholder: "Last Name", class: "form-control"%></div>
          <div class="form-signin"><%= u.text_field :username, placeholder: "Username", class: "form-control"%></div>
          <div class="form-signin"><%= u.email_field :email, placeholder: "Email", class: "form-control"%></div>
          <div class="form-signin"><%= u.password_field :password, placeholder: "Password", class: "form-control"%></div>
          <div class="form-signin"><%= u.password_field :password_confirmation, placeholder: "Password Confirmation", class: "form-control"%></div>
          <div class="form-signin"><%= u.text_field :location_string, placeholder: "Your Location EX: Brooklyn, NY", class: "form-control"%></div>
          <div class="form-signin"><%= u.file_field :avatar, class: "form-control"%></div>
          <div class="form-signin"><%= u.submit class: "btn btn-lg btn-primary btn-block" %></div>
        <% end %>
      </div>
          <div class="form-signin sign-up-now text-center">
            <p>Already have an account? &nbsp <%= link_to "Login now!", login_path%></p>
          </div>
    </div>
</div>

app/views/users/show.html.erb
<div class="jumbotron container-margin">
  <div class="container text-center">
    <h1 class="display-4 underline">Account Settings</h1>
  </div>
</div>

<div class="container">
  <div class="row">
      <div class="col-lg-4">
        <div class="list-group">
          <p class="list-group-item list-group-item-action"><%= image_tag(@user.avatar) if @user.avatar.attached?%></p>
          <p class="list-group-item list-group-item-action">First Name: <%= @user.first_name %></p>
          <p class="list-group-item list-group-item-action">Last Name: <%= @user.last_name %></p>
          <p class="list-group-item list-group-item-action">Email: <%= @user.email %></p>
          <p class="list-group-item list-group-item-action">Your Location: <%= @user.location_string %></p>
        </div>
      </div>
      <div class="col-md-4" style="margin: 0;">
        <% locprofi = Location.create(address: @user.location_string )%>
        <iframe width="300" height="300" frameborder="0" style="border:0"
        src="https://www.google.com/maps/embed/v1/place?key=<%= ENV["GOOGLE_API_KEY"] %>&q=<%= locprofi.latitude %>,<%= locprofi.longitude %>"
        allowfullscreen>
      </iframe>
    </div>
    <div class="col-lg-4">
      <div class="list-group text-center">
        <p class="list-group-item list-group-item-action list-group-item-info"><%= link_to "Find a Date", new_post_path %></p>
        <p class="list-group-item list-group-item-action list-group-item-warning">  <%= link_to 'Edit Account', edit_user_path %></p>
        <p class="list-group-item list-group-item-action list-group-item-danger"><%= link_to "Delete Your Account", @user, class:"danger-text",method: :delete,
        data: { confirm: "YOU CANNOT REVERSE THIS.  Are you sure you want to do this?" } %></p>
      </div>
    </div>
  </div>
</div>

<div class="jumbotron mt-5">
  <div class="container text-center">
    <h1 class="display-4 underline">Your Posts</h1>
  </div>
</div>

<div class="container">
  <% @user.posts.reverse.each do |post|%>
  <div class="row">
      <div class="col-lg-4">
        <div class="list-group">
          <p class="list-group-item list-group-item-action"><%= image_tag (post.picture) if post.picture.attached? %></p>
          <p class="list-group-item list-group-item-action">Title: <%= post.name %></p>
          <p class="list-group-item list-group-item-action">Description: <%= post.description %></p>
          <p class="list-group-item list-group-item-action">Location: <%= post.location_string%></p>
        </div>
      </div>
      <div class="col-md-4" style="margin: 0;">
        <% pocprofi = Location.create(address: post.location_string )%>

        <iframe width="300" height="300" frameborder="0" style="border:0"
        src="https://www.google.com/maps/embed/v1/place?key=<%= ENV["GOOGLE_API_KEY"] %>&q=<%= pocprofi.latitude %>,<%= pocprofi.longitude %>"
        allowfullscreen>
      </iframe>
    </div>
    <div class="col-lg-4">
      <div class="list-group text-center">
        <p class="list-group-item list-group-item-action list-group-item-info"><%= link_to 'Edit Post', edit_post_path(post) %></p>
        <p class="list-group-item list-group-item-action list-group-item-danger"><%= link_to "Delete", post, class:"danger-text", method: :delete, data: { confirm: "You sure?" } %></p>
      </div>
    </div>
  </div>
  <hr class="hr-color">
  <% end %>
</div>