config/routes.rb
Rails.application.routes.draw do

# Serve websocket cable requests in-process
 mount ActionCable.server => '/cable'

 # root 'pages#home'
 root 'pages#home'

resources :posts
resources :locations
resources :messages, only:[:create]
resources :sessions, only:[:new, :destroy, :create]

resources :users do
  resources :chats, only: [:index, :show, :create]
end


  get '/signup', to: 'users#new'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'





end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :picture
  belongs_to :user, optional: true

  validates :name, presence: true
  validates_length_of :name, :maximum => 20;
  validates :description, presence: true
  validates :purchased, default: false
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @user = User.find(session[:user_id])
    @user.posts << @post
    if @post.valid?
      @post.save
      flash[:notice] = "Puppy Date Activated!"
      redirect_to @user
    else
      puts "#{@post.errors.messages}"
      flash[:notice] = "#{@post.errors.messages}"
      render 'new'
    end
  end

  def show
    if current_user != nil
     @post = Post.find_by(id: params[:id])
    else
     redirect_to root_path
   end
  end

  def edit
    if logged_in?
    @post =  Post.find_by(id: params[:id])
  else
    redirect_to root_path
  end
end

  def update
    @post = Post.find_by(id: params[:id])
      if @post.update(post_edit_params)
        flash[:notice] = "Sweet! Post is now looking better than ever!"
        redirect_to user_path
      else
        puts "#{@post.errors.messages}"
        render 'new'
      end
  end

  def index
    p ActiveStorage
    if current_user != nil
     # @post = Post.paginate(page: params[:page], per_page: 20)
     @posts  = Post.all
   else
     redirect_to root_path
   end
  end

  def destroy
  @post = Post.find(params[:id])
    respond_to do |format|
     format.html { redirect_to posts_url, notice: 'Post was successfully deleted' }
     format.js
   end
   @post.destroy
  end


  private

  def post_params
    params.require(:post).permit(:name, :description, :picture, :location_string)
  end

  def post_edit_params
    params.require(:post).permit(:name, :description, :purchased, :picture, :location_string)
  end


end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/destroy.js.erb
$('.delete').bind('ajax:sucess')

app/views/posts/edit.html.erb
<div class="container mx-auto container-margin">
  <h1 class="font-weight-normal text-center mb-3">Edit Post</h1>
  <div class="row">
    <div class="col-md-12 form-signin ">
      <%= form_for(@post) do |post| %>
        <div class="form-signin"><%= post.text_field :name, placeholder: "ex. Puppy needs a new friend!", class: "form-control"%></div>
        <div class="form-signin"><%= post.text_area :description, placeholder: "Where do you wanna go and/or meetup. What does your pupper like to do?", class: "form-control"%></div>
        <div class="form-signin"><%= post.text_field :location_string, placeholder: "Where would you like to meet?", class: "form-control" %></div>
        <div class="form-signin"><%= post.file_field :picture, direct_upload: true, id: "fileupload", class: "form-control" %></div>
        <div class="form-signin"> <%= post.submit class: "btn btn-lg btn-primary btn-block special-btn-color" %></div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="jumbotron jumbotron-margin">
  <div class="container text-center">
    <h1 class="display-4 underline">All Postings</h1>
  </div>
</div>

<div class="container">
  <% @posts.reverse.each do |post|%>
  <div class="row">
    <div class="col-lg-4">
      <div class="list-group">
        <p class="list-group-item list-group-item-action"><%= image_tag (post.picture) if post.picture.attached? %></p>
        <p class="list-group-item list-group-item-action">Title: <%= post.name %></p>
        <p class="list-group-item list-group-item-action">Description: <%= post.description %></p>
        <p class="list-group-item list-group-item-action">Location: <%= post.location_string%></p>
      </div>
    </div>
    <div class="col-md-4" style="margin: 0;">
      <% pocprofi = Location.create(address: post.location_string )%>
      <iframe width="300" height="300" frameborder="0" style="border:0"
      src="https://www.google.com/maps/embed/v1/place?key=<%= ENV["GOOGLE_API_KEY"] %>&q=<%= pocprofi.latitude %>,<%= pocprofi.longitude %>"
      allowfullscreen>
      </iframe>
  </div>

  <% if session[:user_id] == post.user.id %>
  <div class="col-lg-4">
    <div class="list-group text-center">
      <p class="list-group-item list-group-item-action list-group-item-warning"><%= link_to 'Edit Post', edit_post_path(post) %></p>
    </div>
  </div>
  <% end %>
  <% unless session[:user_id] == post.user.id %>

  <div class="col-lg-4">
    <div class="list-group text-center">
      <p class="list-group-item list-group-item-action list-group-item-info"><%= link_to("Contact User", user_chats_path(current_user, :other_user => post.user.id, :post => post.id), method: :post) %><br>
      </div>
    </div>
    <% end %>
  </div>
  <hr class="hr-color">
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="container mx-auto container-margin">
  <h1 class="font-weight-normal text-center mb-3">Create a Posting</h1>
  <div class="row">
    <div class="col-md-12 form-signin ">
      <%= form_for(@post) do |post| %>
        <div class="form-signin"><%= post.text_field :name, placeholder: "ex. Puppy needs a new friend!", class: "form-control" %></div>
        <div class="form-signin"><%= post.text_area :description, placeholder: "Where do you wanna go and/or meetup. What does your pupper like to do?", class: "form-control" %></div>
        <div class="form-signin"><%= post.text_field :location_string, placeholder: "Where would you like to meet?", class: "form-control" %></div>
        <div class="form-signin"><%= post.file_field :picture, class: "form-control" %></div>
        <div class="form-signin"><%= post.submit class: "btn btn-lg btn-primary btn-block special-btn-color" %></div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
  <%if session[:user_id] == @post.user.id%>

  <p><strong>Title: </strong><%= @post.name %></p>
  <p><strong>Description: </strong><%= @post.description%></p>
  <p><strong>Location: </strong><%= @post.location_string %></p>


  <% end %>
  <% locprofi = Location.create(address: @post.location_string )%>
  <iframe width="300" height="300" frameborder="0" style="border:0"
   src="https://www.google.com/maps/embed/v1/place?key=<%= ENV["GOOGLE_API_KEY"] %>&q=<%= locprofi.latitude %>,<%= locprofi.longitude %>"
   allowfullscreen>
  </iframe>